libguestfs: Fix the missing argument of prepare_attached_device
guestfs_volume_operations and guestfs_volume_operations are fails as 'prepare_attached_device()
missing 1 required positional argument'

  # avocado run --vt-type=libguestfs type_specific.io-github-autotest-libvirt.guestfs_volume_operations.create_volume
  JOB ID     : c071858d0cc1c34a13616637d37b437300ef4e62
  JOB LOG    : /root/avocado/job-results/job-2021-12-10T10.17-c071858/job.log
   (1/1) type_specific.io-github-autotest-libvirt.guestfs_volume_operations.create_volume: STARTED
   (1/1) type_specific.io-github-autotest-libvirt.guestfs_volume_operations.create_volume: ERROR: prepare_attached_device() missing 1 required positional argument: 'device' (175.78 s)
  RESULTS    : PASS 0 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
  JOB TIME   : 185.55 s
  #

Fix the argument.

Signed-off-by: Masayoshi Mizuma <m.mizuma@jp.fujitsu.com>